export enum WISHLIST_ACTION_TYPES {
    SET_IS_WISHLIST_OPEN = 'wishlist/SET_IS_WISHLIST_OPEN',
    SET_WISHLIST_ITEMS = 'wishlist/SET_WISHLIST_ITEMS',
    SET_IS_WISHLIST_LOADED = 'wishlist/SET_IS_WISHLIST_LOADED',
    FETCH_USER_WISHLIST = 'wishlist/FETCH_USER_WISHLIST',
    SAVE_USER_WISHLIST = 'wishlist/SAVE_USER_WISHLIST'
}
